### ISSUE TITLE
Make Mensa Selectable

### ISSUE THREAD

**Issue by dustsucker** [lomenzel/mensa#3]
Make Settings entry to select mensa location.

**Comment by lomenzel** [comment]
Klingt vernünftig, ich glaube die Mensa API unterstützt das zur Zeit noch nicht, sollte aber kein Problem sein, das zu ergänzen, btw, Einstellungen generell wären nice, also auch auswählen können welcher Preis angezeigt werden soll, oder nach Allergenen filtern etc
